# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetOrdering' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GetOrdering
	pod "AFNetworking", "~> 2.0"
        pod 'UIFloatLabelTextField'
        pod 'MBProgressHUD', '~> 1.1.0'
	pod 'SDWebImage/WebP'
end
